version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: "Build Maven"
          command: |
            mvn -B clean package
      - store_test_results:
        path: target/surefire-reports
